FROM mcr.microsoft.com/mssql/server:2019-latest

USER root

RUN apt-get -y update  && \
        apt-get install -y curl && \
        curl -sL https://deb.nodesource.com/setup_14.x | bash - 

COPY ./db/mssql/init/. /usr/src/app

RUN chmod +x /usr/src/app/mssql-entrypoint.sh

USER mssql

# CMD /bin/bash ./entrypoint.sh